# Generated by Django 6.0.2 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.FloatField(default=0),
        ),
    ]
